# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/isaac/Nextcloud/School/W19/CIS4450/code/go_fish/ui/go_fish.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1067, 935)
        MainWindow.setMinimumSize(QtCore.QSize(700, 500))
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Canada))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(-1, 6, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lyout_bot_output_out = QtWidgets.QHBoxLayout()
        self.lyout_bot_output_out.setSpacing(6)
        self.lyout_bot_output_out.setObjectName("lyout_bot_output_out")
        self.frame_bot_output = QtWidgets.QFrame(self.centralwidget)
        self.frame_bot_output.setObjectName("frame_bot_output")
        self.lyout_bot_output_in = QtWidgets.QHBoxLayout(self.frame_bot_output)
        self.lyout_bot_output_in.setObjectName("lyout_bot_output_in")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_bot_output)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.te_output_bot1 = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.te_output_bot1.setReadOnly(True)
        self.te_output_bot1.setObjectName("te_output_bot1")
        self.verticalLayout_3.addWidget(self.te_output_bot1)
        self.lyout_bot_output_in.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_bot_output)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.te_output_bot2 = QtWidgets.QPlainTextEdit(self.groupBox_4)
        self.te_output_bot2.setReadOnly(True)
        self.te_output_bot2.setObjectName("te_output_bot2")
        self.verticalLayout_11.addWidget(self.te_output_bot2)
        self.lyout_bot_output_in.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_bot_output)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.te_output_bot3 = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.te_output_bot3.setReadOnly(True)
        self.te_output_bot3.setObjectName("te_output_bot3")
        self.verticalLayout_6.addWidget(self.te_output_bot3)
        self.lyout_bot_output_in.addWidget(self.groupBox_3)
        self.lyout_bot_output_out.addWidget(self.frame_bot_output)
        self.verticalLayout_2.addLayout(self.lyout_bot_output_out)
        self.lyout_bottom = QtWidgets.QHBoxLayout()
        self.lyout_bottom.setSpacing(6)
        self.lyout_bottom.setObjectName("lyout_bottom")
        self.hand_cards_layout = QtWidgets.QVBoxLayout()
        self.hand_cards_layout.setObjectName("hand_cards_layout")
        self.cards_hand_grp = QtWidgets.QGroupBox(self.centralwidget)
        self.cards_hand_grp.setFlat(False)
        self.cards_hand_grp.setObjectName("cards_hand_grp")
        self.card_hands_layout = QtWidgets.QVBoxLayout(self.cards_hand_grp)
        self.card_hands_layout.setObjectName("card_hands_layout")
        self.radioButton_3 = QtWidgets.QRadioButton(self.cards_hand_grp)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.card_hands_layout.addWidget(self.radioButton_3)
        self.card_1 = QtWidgets.QRadioButton(self.cards_hand_grp)
        self.card_1.setChecked(False)
        self.card_1.setObjectName("card_1")
        self.card_hands_layout.addWidget(self.card_1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.cards_hand_grp)
        self.radioButton_2.setObjectName("radioButton_2")
        self.card_hands_layout.addWidget(self.radioButton_2)
        self.radioButton_4 = QtWidgets.QRadioButton(self.cards_hand_grp)
        self.radioButton_4.setObjectName("radioButton_4")
        self.card_hands_layout.addWidget(self.radioButton_4)
        self.hand_cards_layout.addWidget(self.cards_hand_grp)
        self.groupBox_10 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.lcd_cards_remaining = QtWidgets.QLCDNumber(self.groupBox_10)
        self.lcd_cards_remaining.setDigitCount(2)
        self.lcd_cards_remaining.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_cards_remaining.setObjectName("lcd_cards_remaining")
        self.verticalLayout_15.addWidget(self.lcd_cards_remaining)
        self.hand_cards_layout.addWidget(self.groupBox_10)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.hand_cards_layout.addItem(spacerItem)
        self.lyout_bottom.addLayout(self.hand_cards_layout)
        self.bot_btn_layout = QtWidgets.QVBoxLayout()
        self.bot_btn_layout.setObjectName("bot_btn_layout")
        self.grp_ask = QtWidgets.QGroupBox(self.centralwidget)
        self.grp_ask.setAlignment(QtCore.Qt.AlignCenter)
        self.grp_ask.setObjectName("grp_ask")
        self.lyout_ask = QtWidgets.QVBoxLayout(self.grp_ask)
        self.lyout_ask.setObjectName("lyout_ask")
        self.btn_ask_bot1 = QtWidgets.QPushButton(self.grp_ask)
        self.btn_ask_bot1.setObjectName("btn_ask_bot1")
        self.lyout_ask.addWidget(self.btn_ask_bot1)
        self.btn_ask_bot2 = QtWidgets.QPushButton(self.grp_ask)
        self.btn_ask_bot2.setObjectName("btn_ask_bot2")
        self.lyout_ask.addWidget(self.btn_ask_bot2)
        self.btn_ask_bot3 = QtWidgets.QPushButton(self.grp_ask)
        self.btn_ask_bot3.setObjectName("btn_ask_bot3")
        self.lyout_ask.addWidget(self.btn_ask_bot3)
        self.bot_btn_layout.addWidget(self.grp_ask)
        self.grp_hands = QtWidgets.QGroupBox(self.centralwidget)
        self.grp_hands.setObjectName("grp_hands")
        self.lyout_hands = QtWidgets.QVBoxLayout(self.grp_hands)
        self.lyout_hands.setObjectName("lyout_hands")
        self.groupBox_6 = QtWidgets.QGroupBox(self.grp_hands)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lcd_cards_bot1 = QtWidgets.QLCDNumber(self.groupBox_6)
        self.lcd_cards_bot1.setDigitCount(2)
        self.lcd_cards_bot1.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_cards_bot1.setObjectName("lcd_cards_bot1")
        self.verticalLayout.addWidget(self.lcd_cards_bot1)
        self.lyout_hands.addWidget(self.groupBox_6)
        self.groupBox_8 = QtWidgets.QGroupBox(self.grp_hands)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lcd_cards_bot2 = QtWidgets.QLCDNumber(self.groupBox_8)
        self.lcd_cards_bot2.setDigitCount(2)
        self.lcd_cards_bot2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_cards_bot2.setObjectName("lcd_cards_bot2")
        self.verticalLayout_10.addWidget(self.lcd_cards_bot2)
        self.lyout_hands.addWidget(self.groupBox_8)
        self.groupBox_9 = QtWidgets.QGroupBox(self.grp_hands)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.lcd_cards_bot3 = QtWidgets.QLCDNumber(self.groupBox_9)
        self.lcd_cards_bot3.setDigitCount(2)
        self.lcd_cards_bot3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_cards_bot3.setObjectName("lcd_cards_bot3")
        self.verticalLayout_14.addWidget(self.lcd_cards_bot3)
        self.lyout_hands.addWidget(self.groupBox_9)
        self.bot_btn_layout.addWidget(self.grp_hands)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.bot_btn_layout.addItem(spacerItem1)
        self.lyout_bottom.addLayout(self.bot_btn_layout)
        self.frame_pairs = QtWidgets.QFrame(self.centralwidget)
        self.frame_pairs.setLineWidth(0)
        self.frame_pairs.setObjectName("frame_pairs")
        self.lyout_pairs = QtWidgets.QGridLayout(self.frame_pairs)
        self.lyout_pairs.setObjectName("lyout_pairs")
        self.frame = QtWidgets.QFrame(self.frame_pairs)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.score_player = QtWidgets.QLCDNumber(self.frame)
        self.score_player.setDigitCount(2)
        self.score_player.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.score_player.setObjectName("score_player")
        self.horizontalLayout_5.addWidget(self.score_player)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.te_pairs_player = QtWidgets.QPlainTextEdit(self.frame)
        self.te_pairs_player.setReadOnly(True)
        self.te_pairs_player.setObjectName("te_pairs_player")
        self.verticalLayout_5.addWidget(self.te_pairs_player)
        self.lyout_pairs.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_pairs)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.score_bot1 = QtWidgets.QLCDNumber(self.frame_4)
        self.score_bot1.setDigitCount(2)
        self.score_bot1.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.score_bot1.setObjectName("score_bot1")
        self.horizontalLayout_6.addWidget(self.score_bot1)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.te_pairs_bot1 = QtWidgets.QPlainTextEdit(self.frame_4)
        self.te_pairs_bot1.setReadOnly(True)
        self.te_pairs_bot1.setObjectName("te_pairs_bot1")
        self.verticalLayout_12.addWidget(self.te_pairs_bot1)
        self.lyout_pairs.addWidget(self.frame_4, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame_pairs)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11, 0, QtCore.Qt.AlignRight)
        self.score_bot3 = QtWidgets.QLCDNumber(self.frame_3)
        self.score_bot3.setDigitCount(2)
        self.score_bot3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.score_bot3.setObjectName("score_bot3")
        self.horizontalLayout_4.addWidget(self.score_bot3, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_13.addLayout(self.horizontalLayout_4)
        self.te_pairs_bot3 = QtWidgets.QPlainTextEdit(self.frame_3)
        self.te_pairs_bot3.setReadOnly(True)
        self.te_pairs_bot3.setObjectName("te_pairs_bot3")
        self.verticalLayout_13.addWidget(self.te_pairs_bot3)
        self.lyout_pairs.addWidget(self.frame_3, 1, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame_pairs)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10, 0, QtCore.Qt.AlignRight)
        self.score_bot2 = QtWidgets.QLCDNumber(self.frame_2)
        self.score_bot2.setDigitCount(2)
        self.score_bot2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.score_bot2.setObjectName("score_bot2")
        self.horizontalLayout_3.addWidget(self.score_bot2, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.te_pairs_bot2 = QtWidgets.QPlainTextEdit(self.frame_2)
        self.te_pairs_bot2.setReadOnly(True)
        self.te_pairs_bot2.setObjectName("te_pairs_bot2")
        self.verticalLayout_9.addWidget(self.te_pairs_bot2)
        self.lyout_pairs.addWidget(self.frame_2, 1, 0, 1, 1)
        self.lyout_bottom.addWidget(self.frame_pairs)
        self.grp_player_output = QtWidgets.QGroupBox(self.centralwidget)
        self.grp_player_output.setObjectName("grp_player_output")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.grp_player_output)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.te_player_output = QtWidgets.QPlainTextEdit(self.grp_player_output)
        self.te_player_output.setReadOnly(True)
        self.te_player_output.setObjectName("te_player_output")
        self.verticalLayout_7.addWidget(self.te_player_output)
        self.lyout_bottom.addWidget(self.grp_player_output)
        self.verticalLayout_2.addLayout(self.lyout_bottom)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1067, 32))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionSave_Game = QtWidgets.QAction(MainWindow)
        self.actionSave_Game.setObjectName("actionSave_Game")
        self.actionOpen_Game = QtWidgets.QAction(MainWindow)
        self.actionOpen_Game.setObjectName("actionOpen_Game")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionNew_Game = QtWidgets.QAction(MainWindow)
        self.actionNew_Game.setObjectName("actionNew_Game")
        self.actionPrint_hand_to_JSON = QtWidgets.QAction(MainWindow)
        self.actionPrint_hand_to_JSON.setObjectName("actionPrint_hand_to_JSON")
        self.menuFile.addAction(self.actionNew_Game)
        self.menuFile.addAction(self.actionSave_Game)
        self.menuFile.addAction(self.actionOpen_Game)
        self.menuFile.addAction(self.actionPrint_hand_to_JSON)
        self.menuFile.addAction(self.actionExit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Go Fish"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Bot 1 Output"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Bot 2 Output"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Bot 3 Output"))
        self.cards_hand_grp.setTitle(_translate("MainWindow", "Cards in Hand"))
        self.radioButton_3.setText(_translate("MainWindow", "&Card 1"))
        self.card_1.setText(_translate("MainWindow", "Card &2"))
        self.radioButton_2.setText(_translate("MainWindow", "Card &3"))
        self.radioButton_4.setText(_translate("MainWindow", "Card &4"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Remaining Fish"))
        self.grp_ask.setTitle(_translate("MainWindow", "Bot to Ask"))
        self.btn_ask_bot1.setText(_translate("MainWindow", "Bot 1"))
        self.btn_ask_bot2.setText(_translate("MainWindow", "Bot 2"))
        self.btn_ask_bot3.setText(_translate("MainWindow", "Bot 3"))
        self.grp_hands.setTitle(_translate("MainWindow", "Cards in Bot hands"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Bot 1"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Bot 2"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Bot 3"))
        self.label_8.setText(_translate("MainWindow", "Your Pairs"))
        self.label_13.setText(_translate("MainWindow", "Score:"))
        self.label_9.setText(_translate("MainWindow", "Bot 1 Pairs"))
        self.label_12.setText(_translate("MainWindow", "Score:"))
        self.label_7.setText(_translate("MainWindow", "Bot 3 Pairs"))
        self.label_11.setText(_translate("MainWindow", "Score:"))
        self.label_6.setText(_translate("MainWindow", "Bot 2 Pairs"))
        self.label_10.setText(_translate("MainWindow", "Score:"))
        self.grp_player_output.setTitle(_translate("MainWindow", "Player Output"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.actionSave_Game.setText(_translate("MainWindow", "&Save Game"))
        self.actionOpen_Game.setText(_translate("MainWindow", "&Open Game"))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionNew_Game.setText(_translate("MainWindow", "&New Game"))
        self.actionPrint_hand_to_JSON.setText(_translate("MainWindow", "Print hand to JSON"))

